Converting to functions and adding logic to track branches

diff --git a/git-svn-clone-externals b/git-svn-clone-externals
--- a/git-svn-clone-externals
+++ b/git-svn-clone-externals
@@ -1,18 +1,5 @@
 #!/bin/bash
 
-set -e
-
-toplevel_directory="$(git rev-parse --show-cdup)"
-[ -n "$toplevel_directory" ] && { echo "please run from the toplevel directory"; exit 1; }
-
-function isWindows() { [[ -n "$WINDIR" ]]; }
-
-if isWindows; then
-    if ! net session &> /dev/null; then
-        echo 'Please run as administrator! It is required to create symbolic links.'; exit 1;
-    fi
-fi
-
 function call()
 {
     cmd="$@"
@@ -21,12 +8,13 @@ function call()
     return "$?"
 }
 
+source "./git-svn-externals-include"
 
 function do_clone()
 {
     test -d .git_externals || return 1
     
-    cd .git_externals
+    cd ".git_externals/$(get_branch)"
 
     #Scape spaces in the path with backslash
     destination_scaped="$(echo ${destination} | sed -E 's/ /\\ /g')" 
@@ -39,7 +27,7 @@ function do_clone()
         (
             echo "fetching all ... " $destination 
             cd "$destination"
-            call git svn fetch --all
+            call git svn fetch -r HEAD
         )
     else
         
@@ -48,43 +36,15 @@ function do_clone()
     
 }
 
-function do_link()
-{
-    
-    dir="$1"
-    
-    #Return to the top level directory
-    top=$(git rev-parse --show-cdup)
-    cd "$top" 
-
-    base=$(dirname "$dir")
-    (
-        mkdir -p "$base"
-        cd "$base"
-        destFolder=$(basename "$dir")
-        
-        if [[ -d "$destFolder" ]] || [[ -L "$destFolder" ]]; then
-            rm -rf "$destFolder"     
-        fi
-
-        top=$(git rev-parse --show-cdup)
-
-        if isWindows; then
-            link_des_windows=$(cygpath -w "${top}.git_externals/${dir}")
-            cmd <<< "mklink /D \"${destFolder%/}\" \"${link_des_windows%/}\"" > /dev/null
-        else
-            ln -s "${top}.git_externals/${dir}" "$destFolder"
-        fi
-    )
-}
-
 function do_excludes()
 {
-     #Return to the top level directory
+    #Return to the top level directory
     top=$(git rev-parse --show-cdup)
     cd "$top"
 
-    dir="$1"
+    #Scape spaces in the path with backslash and remove the firt dot and slash
+    dir=$(echo "${1}" | sed -E 's/ /\\ /g' | sed s_^\.\/__) 
+    echo "Excluding $dir"
     git_excludes_path=.git/info/exclude
     if ! grep -q '^.git_externals$' "$git_excludes_path"
     then
@@ -110,92 +70,110 @@ function is_excluded()
     return
 }
 
+function git_svn_clone_externals()
+{
+	set -e
 
-git svn show-externals | grep -vE '#|^$' | \
-    sed 's/\(-r\)[ ]*\([0-9]\{1,\}\)/\1\2/' | \
-    while read svn_externals
-do
-    echo $svn_externals
-        
-    # First get the local directory in which the external was defined
-    local_directory="$(echo ${svn_externals} | sed -r 's_\/(\.\.|\^|)\/.*__' )" 
-    
-    echo "Local directory ${local_directory}"
+	toplevel_directory="$(git rev-parse --show-cdup)"
+	[ -n "$toplevel_directory" ] && { echo "please run from the toplevel directory"; exit 1; }
 
-    # Now remove the local directory from the line and see what else we have
-    local_directory_scaped="$(echo ${local_directory} | sed -r 's_\/_\\/_g')" 
-    if [ -n "${local_directory_scaped}" ] ; then
-        otherArguments="$(echo ${svn_externals} | sed -r "s_${local_directory_scaped}__")" 
-    else
-        otherArguments="${svn_externals}" 
-    fi
-    
-    number_fields="$(echo ${otherArguments}|awk '{print NF}')"
-    case $number_fields in
-        2)
-            revision=""
-            remote_url="$(echo ${otherArguments} | awk '{print $1}')"
-            local_folder="$(echo ${otherArguments} | awk '{print $2}')"
-            ;;
-        3)
-            revision=""$(echo ${otherArguments} | awk '{print $3}')
-            remote_url="$(echo ${otherArguments} | awk '{print $1}')"
-            local_folder="$(echo ${otherArguments} | awk '{print $2}')"
-            ;;
-        *) continue ;;
-    esac
-    
-    echo "Preprocessed remote ${remote_url}"
+	if isWindows; then
+	    if ! net session &> /dev/null; then
+	        echo 'Please run as administrator! It is required to create symbolic links.'; exit 1;
+	    fi
+	fi
 
-    destination=".${local_directory}/${local_folder}"
-    
-    check_excluded=$(is_excluded $destination)
-    if [ $check_excluded -eq 0 ] ; then
-	
-        if [[ $remote_url == /../* ]]; then
-            # We have relative paths in the remote Url.
-            # Get rid of them using readlink 
-            base_url=$(git svn info | grep 'URL: ' | sed -r 's_URL: __')
-            canonicalPath=$(readlink -m "$local_directory$remote_url")
-            remote_url=$base_url$canonicalPath
-        fi
+	git svn show-externals | grep -vE '#|^$' | \
+		sed 's/\(-r\)[ ]*\([0-9]\{1,\}\)/\1\2/' | \
+		while read svn_externals
+	do
+		echo $svn_externals
+			
+		# First get the local directory in which the external was defined
+		local_directory="$(echo ${svn_externals} | sed -r 's_\/(\.\.|\^|)\/.*__' )" 
+		
+		echo "Local directory ${local_directory}"
 
-        if [[ $remote_url == //* ]]; then
-            #  In this case the path relates to the same server
-            root_url=$(git svn info | grep 'Repository Root: ' | sed -r 's_Repository Root: __')
-            svn_server=$(echo $root_url | awk -F/ '{print $3}')
-            protocol=$(echo $root_url | awk -F/ '{print $1}')
-            remote_url=${protocol}//${svn_server}${remote_url}
-        fi
+		# Now remove the local directory from the line and see what else we have
+		local_directory_scaped="$(echo ${local_directory} | sed -r 's_\/_\\/_g')" 
+		if [ -n "${local_directory_scaped}" ] ; then
+			otherArguments="$(echo ${svn_externals} | sed -r "s_${local_directory_scaped}__")" 
+		else
+			otherArguments="${svn_externals}" 
+		fi
+		
+		number_fields="$(echo ${otherArguments}|awk '{print NF}')"
+		case $number_fields in
+			2)
+				revision=""
+				remote_url="$(echo ${otherArguments} | awk '{print $1}')"
+				local_folder="$(echo ${otherArguments} | awk '{print $2}')"
+				;;
+			3)
+				revision=""$(echo ${otherArguments} | awk '{print $3}')
+				remote_url="$(echo ${otherArguments} | awk '{print $1}')"
+				local_folder="$(echo ${otherArguments} | awk '{print $2}')"
+				;;
+			*) continue ;;
+		esac
+		
+		echo "Preprocessed remote ${remote_url}"
 
-        if [[ $remote_url == /^/* ]]; then
-            root_url=$(git svn info | grep 'Repository Root: ' | sed -r 's_Repository Root: __')
-            remote_url=$(echo $remote_url | sed -r 's_\^/__')
-            remote_url=${root_url}${remote_url}
-        fi
+		destination=".${local_directory}/${local_folder}"
+		
+		check_excluded=$(is_excluded $destination)
+		if [ $check_excluded -eq 0 ] ; then
+		
+			if [[ $remote_url == /../* ]]; then
+				# We have relative paths in the remote Url.
+				# Get rid of them using readlink 
+				base_url=$(git svn info | grep 'URL: ' | sed -r 's_URL: __')
+				canonicalPath=$(readlink -m "$local_directory$remote_url")
+				remote_url=$base_url$canonicalPath
+			fi
 
-        if [ -n "$USE_SSH" ]; then
-            echo "Rewriting url to use SVN+SSH."
-            shopt -s extglob
-            remote_url="${remote_url/+(http|https)/svn+ssh}"
-        fi
+			if [[ $remote_url == //* ]]; then
+				#  In this case the path relates to the same server
+				root_url=$(git svn info | grep 'Repository Root: ' | sed -r 's_Repository Root: __')
+				svn_server=$(echo $root_url | awk -F/ '{print $3}')
+				protocol=$(echo $root_url | awk -F/ '{print $1}')
+				remote_url=${protocol}//${svn_server}${remote_url}
+			fi
 
-        [ -z "${remote_url}" ] && continue
+			if [[ $remote_url == /^/* ]]; then
+				root_url=$(git svn info | grep 'Repository Root: ' | sed -r 's_Repository Root: __')
+				remote_url=$(echo $remote_url | sed -r 's_\^/__')
+				remote_url=${root_url}${remote_url}
+			fi
 
-        if [ -n $revision ]; then
-            revision="HEAD"
-        fi
+			if [ -n "$USE_SSH" ]; then
+				echo "Rewriting url to use SVN+SSH."
+				shopt -s extglob
+				remote_url="${remote_url/+(http|https)/svn+ssh}"
+			fi
+
+			[ -z "${remote_url}" ] && continue
+
+			if [ -n $revision ]; then
+				revision="HEAD"
+			fi
 
 
-        export local_directory revision remote_url
-	
-        echo "DESTINATION: $destination -> REVISION: $revision -> REMOTE URL: $remote_url"
+			export local_directory revision remote_url
+		
+			echo "DESTINATION: $destination -> REVISION: $revision -> REMOTE URL: $remote_url"
 
-        dir=`dirname $destination`
-        [ -d ".git_externals/$dir" ] || mkdir -p ".git_externals/$dir"
-        do_clone "$revision" "$remote_url" "$destination" || exit
-        do_link "$destination"
-        do_excludes "$destination"
-    fi
+			dir=`dirname $destination`
+			branch=$(get_branch)
+			[ -d ".git_externals/${branch}/$dir" ] || mkdir -p ".git_externals/${branch}/$dir"
+			echo "Cloning.............................."
+			do_clone "$revision" "$remote_url" "$destination" || exit
+			echo "Linking.............................."
+			do_link "$destination"
+			echo "Excludes............................."
+			do_excludes "$destination"
+			echo "Next item............................"
+		fi
 
-done
+	done
+}
